// Generated by Selenium IDE
package Basepkg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RecTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rec() {
    driver.get("https://www.google.co.in/search?q=car&sca_esv=596463110&sxsrf=AM9HkKm8G1NKgdDUQbYC3gUn6t3DEgV4hw%3A1704691109191&source=hp&ei=pYWbZaOCCcGUg8UPrem98As&iflsig=AO6bgOgAAAAAZZuTtQ6BExcMGkttPxGn4W1524xyJ7un&ved=0ahUKEwjj6Iyghc2DAxVByqACHa10D74Q4dUDCAo&uact=5&oq=car&gs_lp=Egdnd3Mtd2l6IgNjYXIyChAjGIAEGIoFGCcyChAAGIAEGIoFGEMyEBAuGIAEGIoFGEMYxwEY0QMyDRAAGIAEGIoFGEMYyQMyEBAAGIAEGIoFGEMYsQMYgwEyCxAAGIAEGIoFGJIDMgUQABiABDIREC4YgAQYsQMYgwEYxwEY0QMyEBAuGIAEGIoFGEMYxwEY0QMyCBAAGIAEGLEDSLscUABYvgNwAHgAkAEAmAGYAaABrQOqAQMwLjO4AQPIAQD4AQHCAgQQIxgnwgILEAAYgAQYsQMYgwHCAggQLhiABBjUAsICDhAuGIAEGIoFGLEDGIMBwgIKEC4YgAQYigUYQ8ICFhAuGIAEGIoFGEMYsQMYgwEYxwEY0QPCAgsQLhiABBixAxiDAQ&sclient=gws-wiz");
    driver.findElement(By.xpath("//div[@id=\'rso\']/div/div/div/div/div/div/div/span/a/h3")).click();
  }
}
